# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.IntegerField(unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
